### ISSUE TITLE
Pagination bug

### ISSUE THREAD

**Issue by armsnyder** [Shresht7/label-sync-action#2]
I tried this action on a repository with 43 labels (more than the default API page size of 30) and in the dry-run it shows it is creating the 13 labels on the second page.

Note that all of these labels exist.

<img width="481" alt="Screen Shot 2022-01-31 at 8 15 23 PM" src="https://user-images.githubusercontent.com/9969202/151911953-fa0acb5e-b959-4697-8ba7-33a8213a34a3.png">

**Comment by Shresht7** [comment]
Hi, thanks for the report! Should be a simple fix.

**Comment by Shresht7** [comment]
@armsnyder , this should work for any number of labels now.
You'll need to target `v1.0.1` in the yaml config.

**Comment by armsnyder** [comment]
Thanks for the quick fix!
